AzureAD/azure-activedirectory-library-for-dotnet

ADAL.NET.sln
src/ADAL.PCL.iOS/ADAL.PCL.iOS.csproj
src/ADAL.PCL.iOS/AuthenticationAgentUINavigationController.cs
src/ADAL.PCL.iOS/AuthenticationAgentUIViewController.cs
src/ADAL.PCL.iOS/AuthorizationParameters.cs
tests/TestApp/AdaliOSTestApp/AdaliOSTestApp.csproj
tests/TestApp/AdaliOSTestApp/AdaliOSTestAppViewController.cs
tests/TestApp/AdaliOSTestApp/AdaliOSTestAppViewController.designer.cs
tests/TestApp/AdaliOSTestApp/AppDelegate.cs
tests/TestApp/AdaliOSTestApp/Main.cs

<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/154?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/154'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Switching ADAL iOS from classic to unified API

---

src/ADAL.PCL/AcquireTokenByAuthorizationCodeHandler.cs
src/ADAL.PCL/AcquireTokenHandlerBase.cs
src/ADAL.PCL/TokenCache.cs
tests/Test.ADAL.Common/AdalTests.cs
tests/Test.ADAL.Common/Sts.cs
tests/Test.ADAL.Common/TokenCacheTests.cs
tests/Test.ADAL.NET.Unit/TokenCacheUnitTests.cs
tests/Test.ADAL.NET/AdalDotNetTests.cs
tests/Test.ADAL.NET/AdalTests.cs
tests/Test.ADAL.WinRT.Unit/TokenCacheUnitTests.cs

<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/181?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/181'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Merging v2 test and logging changes to v3

---

src/ADAL.PCL.Android/WebUI.cs
src/ADAL.PCL.Desktop/WindowsFormsWebAuthenticationDialogBase.cs
src/ADAL.PCL.WinPhone/PlatformInformation.cs
src/ADAL.PCL.WinRT/PlatformInformation.cs
src/ADAL.PCL.iOS/WebUI.cs
src/ADAL.PCL/AcquireTokenByAuthorizationCodeHandler.cs
src/ADAL.PCL/AcquireTokenHandlerBase.cs
src/ADAL.PCL/AcquireTokenInteractiveHandler.cs
src/ADAL.PCL/AuthenticationResultEx.cs
src/ADAL.PCL/OAuthConstants.cs
src/ADAL.PCL/PlatformInformationBase.cs
src/ADAL.PCL/TokenCache.cs
src/ADAL.PCL/TokenResponse.cs
tests/Test.ADAL.Common/AdalTests.cs
tests/Test.ADAL.Common/TokenCacheTests.cs
tests/Test.ADAL.NET.Friend/RecorderWebUI.cs
tests/Test.ADAL.NET.Unit/UnitTests.cs
tests/Test.ADAL.NET/AdalTests.cs
tests/Test.ADAL.WinPhone.Unit/ReplayerWebUI.cs
tests/Test.ADAL.WinRT.Unit/ReplayerWebUI.cs
tests/Test.ADAL.WinRT.Unit/UnitTests.cs

<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/189?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/189'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Fixing #121, #161, #182 and #183 in v3

---

src/ADAL.PCL.Android/ADAL.PCL.Android.csproj
src/ADAL.PCL.Desktop/WindowsFormsWebAuthenticationDialogBase.cs
src/ADAL.PCL.iOS/AuthenticationAgentUIViewController.cs
src/ADAL.PCL/AuthenticationContext.cs
tests/Test.ADAL.NET/Test.ADAL.NET.csproj
tests/TestApp/AdalAndroidTestApp/MainActivity.cs
tests/TestApp/AdalXamarinFormsTestApp.Droid/AdalXamarinFormsTestApp.Droid.csproj
tests/TestApp/AdalXamarinFormsTestApp/packages.config
tests/TestApp/AdaliOSTestApp/AdaliOSTestAppViewController.cs
tests/TestApp/AdaliOSTestApp/AdaliOSTestAppViewController.designer.cs
tests/TestApp/AdaliOSTestApp/MainStoryboard.storyboard
tests/TestApp/TestApp.PCL/TokenBroker.cs

<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/195?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/195'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Fixing bugs #190, #193 and #194

---

src/ADAL.PCL/AcquireTokenHandlerBase.cs

missed changes
<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/204?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/204'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

missed changes

---

src/ADAL.PCL/UserCredential.cs
src/ADAL.PCL/WsTrustRequest.cs
tests/Test.ADAL.NET.Unit/NonInteractiveTests.cs

Issue #207
This has a repro with federated account when user's password contains one of the &,",',<, or >
This is related to wstrust request to get assertion.
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/tushargupta51%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/803796%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/208%23issuecomment-113635184%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-06-19T20%3A39%3A35Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/803796%3Fv%3D3%22%2C%20%22 …

Escape xml chars in password

---

src/ADAL.Common/CommonAssemblyInfo.cs
src/ADAL.Common/WsTrustRequest.cs
src/ADAL.NET/UserCredential.cs

<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/210?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/210'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

update version and use securityelement.escape

---

src/ADAL.PCL/AcquireTokenNonInteractiveHandler.cs
src/ADAL.PCL/AuthenticationContext.cs
tests/Test.ADAL.Common/AdalTests.cs
tests/Test.ADAL.Common/Sts.cs
tests/Test.ADAL.Common/TestMetadata.xml
tests/Test.ADAL.NET/AdalDotNetTests.cs

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/197%23issuecomment-106089252%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/197%23issuecomment-111596296%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/197%23issuecomment-112240032%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/197%23issuecomment-106089252%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Hi%20__%40ptsurbeleu__%2C%20I%27m%20your%20friendly%20neighborhood%20Microsoft%20Open%20Technologies%2C%20Inc.%20Pull%20Request%20Bot%20%28You%20c …

Adding Resource Owner Credentials flow support for ADFS w/ some test coverage

---

README.md

So, this is probably not the best solution, because I don't know what links the author was referring to, and I have no experience in configuring Fiddler. Otherwise I would gladly add them.
The ADAL Android wiki has a similar entry, but points to two wiki pages in the Android repo. The wiki for this project has no such pages.
The Android links:
https://github.com/AzureAD/azure-activedirectory-library-for-android/wiki/How-to-listen-to-httpUrlConnection-in-Android-app-from-Fiddler
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/221%23issuecomment-126194188%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/221%23issuecomment-126777510%22%2C%20%22https%3A//git …

Removed statement that links will follow. Sadly, there are no links. :(

---

ADAL.NET.sln
tests/TestApp/AdalXamarinFormsTestApp.iOS/XFormsApp.iOS.csproj

project rename
<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/228?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/228'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

project rename

---

.gitignore
src/ADAL.PCL.Android/ADAL.PCL.Android.csproj
src/ADAL.PCL.Android/AuthenticationAgentActivity.cs
src/ADAL.PCL.iOS/ADAL.PCL.iOS.csproj
tests/TestApp/AdalAndroidTestApp/AdalAndroidTestApp.csproj
tests/TestApp/AdalAndroidTestApp/Properties/AndroidManifest.xml
tests/TestApp/AdalXamarinFormsTestApp.Droid/AdalXamarinFormsTestApp.Droid.csproj
tests/TestApp/AdalXamarinFormsTestApp.Droid/MainActivity.cs
tests/TestApp/AdalXamarinFormsTestApp.Droid/SecondPageRenderer.cs
tests/TestApp/AdalXamarinFormsTestApp.iOS/AdalXamarinFormsTestApp.iOS.csproj
tests/TestApp/AdalXamarinFormsTestApp/SecondPage.cs
tests/TestApp/AdaliOSTestApp/AdaliOSTestApp.csproj
tests/TestApp/TestApp.PCL/TokenBroker.cs

fix build and xamarin android issue
<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/232?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/232'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

fix build and xamarin android issue

---

src/ADAL.PCL.Android/ADAL.PCL.Android.csproj
tests/TestApp/AdalAndroidTestApp/AdalAndroidTestApp.csproj
tests/TestApp/XFormsApp.Droid/Properties/AndroidManifest.xml
tests/TestApp/XFormsApp.Droid/XFormsApp.Droid.csproj

android build updates
<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/235?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/235'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

android build updates

---

tests/TestApp/XFormsApp.Droid/Properties/AndroidManifest.xml

<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/236?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/236'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

target to API 19

---

src/ADAL.PCL.Android/ADAL.PCL.Android.csproj
src/ADAL.PCL.iOS/TokenCachePlugin.cs
tests/TestApp/AdalAndroidTestApp/AdalAndroidTestApp.csproj

add properties to SecRecord for successful persistence
<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/237?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/237'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

add properties to SecRecord for successful persistence

---

src/ADAL.PCL/AuthenticationContext.cs

Fixes the B2C confidential client sample.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/241%23issuecomment-135905294%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/241%23issuecomment-135905404%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/241%23issuecomment-135905294%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Hi%20__%40dstrockis__%2C%20I%27m%20your%20friendly%20neighborhood%20Microsoft%20Pull%20Request%20Bot%20%28You%20can%20call%20me%20MSBOT%29.%20Thanks%20for%20your%20contribution%21%5Cr%5Cn%20%20%20%20%3Cspan%3E%5Cr%5Cn%2 …

Check out my mad coding skilllz!

---

src/ADAL.PCL.Android/ADAL.PCL.Android.csproj
tests/TestApp/AdalAndroidTestApp/AdalAndroidTestApp.csproj
tests/TestApp/XFormsApp.Droid/Properties/AndroidManifest.xml
tests/TestApp/XFormsApp.Droid/XFormsApp.Droid.csproj

Convergence v4 - Merge to release
<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/245?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/245'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Convergence v4 - Merge to release

---

tests/TestApp/AdalXamarinFormsTestApp/SecondPage.cs
tests/TestApp/AdaliOSTestApp/AdaliOSTestAppViewController.cs
tests/TestApp/TestApp.PCL/TokenBroker.cs

cleanup sample apps
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/weijjia%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1166233%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/253%23issuecomment-146075752%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Looks%20good.%20%3Ashipit%3A%20%22%2C%20%22created_at%22%3A%20%222015-10-07T04%3A44%3A39Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1166233%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/weijjia%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22pro …

cleanup sample apps

---

src/ADAL.PCL.Android/ApplicationReceiver.cs
src/ADAL.PCL.Android/AuthenticationAgentActivity.cs
src/ADAL.PCL.Android/BrokerConstants.cs
src/ADAL.PCL.Android/BrokerProxy.cs
src/ADAL.PCL.Desktop/DeviceAuthHelper.cs
src/ADAL.PCL.WinRT/DeviceAuthHelper.cs
src/ADAL.PCL/Constants.cs

throw when no certificate found + casing fixes
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/weijjia%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1166233%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/260%23issuecomment-148531070%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%20%22%2C%20%22created_at%22%3A%20%222015-10-15T21%3A47%3A33Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1166233%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/weijjia%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D% …

throw when no certificate found + casing fixes

---

src/ADAL.PCL.Android/AuthenticationAgentActivity.cs
src/ADAL.PCL.Android/Constants.cs
src/ADAL.PCL.Android/TokenCachePlugin.cs
src/ADAL.PCL.iOS/ADAL.PCL.iOS.csproj
src/ADAL.PCL.iOS/AdalCustomUrlProtocol.cs
src/ADAL.PCL.iOS/AuthenticationAgentUINavigationController.cs
src/ADAL.PCL.iOS/AuthenticationAgentUIViewController.cs
src/ADAL.PCL.iOS/BrokerConstants.cs
src/ADAL.PCL.iOS/BrokerHelper.cs
src/ADAL.PCL.iOS/Constants.cs
tests/TestApp/AdalAndroidTestApp/MainActivity.cs
tests/TestApp/AdaliOSTestApp/AdaliOSTestAppViewController.cs

Send device auth header correctly in iOS
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/weijjia%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1166233%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/262%23issuecomment-149282406%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%20%22%2C%20%22created_at%22%3A%20%222015-10-19T17%3A02%3A21Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1166233%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/weijjia%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%2C%20%22P …

iOS device auth fix

---

tests/TestApp/AdaliOSTestApp/AdaliOSTestAppViewController.cs
tests/TestApp/AdaliOSTestApp/MainStoryboard.storyboard

checking missing file
<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/267?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/267'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

checking missing file

---

src/ADAL.PCL.Android/ADAL.PCL.Android.csproj
tests/TestApp/AdaliOSTestApp/AdaliOSTestApp.csproj
tests/TestApp/XFormsApp.iOS/XFormsApp.iOS.csproj
tests/TestApp/XFormsApp/App.cs
tests/TestApp/XFormsApp/MainPage.cs
tests/TestApp/XFormsApp/SecondPage.cs

namespace and build fixes
<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/269?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/269'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

namespace and build fixes

---

src/ADAL.PCL/WsTrustRequest.cs

Fix invalid header value

---

src/ADAL.Common/CommonAssemblyInfo.cs
src/ADAL.Common/Constants.cs
src/ADAL.PCL.Android/AuthenticationAgentActivity.cs
src/ADAL.PCL.Android/BrokerHelper.cs
src/ADAL.PCL.Android/BrokerProxy.cs
src/ADAL.PCL.Android/Constants.cs
src/ADAL.PCL.CoreCLR/PlatformInformation.cs
src/ADAL.PCL.Desktop/Native/BCryptNative.cs
src/ADAL.PCL.Desktop/PlatformInformation.cs
src/ADAL.PCL.Desktop/WebUI.cs
src/ADAL.PCL.WinRT/ADAL.PCL.WinRT.csproj
src/ADAL.PCL.iOS/BrokerHelper.cs
src/ADAL.PCL.iOS/Constants.cs
src/ADAL.PCL/Constants.cs
src/ADAL.PCL/PlatformInformationBase.cs
tests/Test.ADAL.NET.Unit/NonInteractiveTests.cs
tests/Test.ADAL.WinRT.Unit/ReplayerHttpClient.cs
tests/Test.ADAL.WinRT.Unit/ReplayerWebUI.cs
tests/TestApp/AdalAndroidTestApp/MainActivity.cs
tests/TestApp/AdalDesktopTestApp/AdalDesktopTestApp.csproj
tests/TestApp/TestApp.PCL/TestApp.PCL.csproj
tests/TestApp/XFormsApp.Droid/MainActivity.cs
tests/TestApp/XFormsApp.iOS/XFormsApp.iOS.csproj

fxcop cleanup

---

src/ADAL.Common/MexParser.cs
src/ADAL.Common/OAuth2Response.cs
tests/Test.ADAL.NET.Unit/NonInteractiveTests.cs

stream seek error and WS-Trust issue fixes

stream seek error and WS-Trust issue fixes

---

src/ADAL.Common/CommonAssemblyInfo.cs
src/ADAL.Common/MexParser.cs

Use SoapAction value to derive if it is a WSTrust 1.3 or 2005 endpoint.

Use SoapAction value to derive if it is a WSTrust 1.3 or 2005 endpoint.

---

src/ADAL.PCL.Android/AuthenticationAgentContinuationHelper.cs
src/ADAL.PCL.Android/BrokerHelper.cs
src/ADAL.PCL.Android/Constants.cs

Dev v3 cert api

---

src/ADAL.Common/TokenCache.cs

added log messages to delete and clear methods in token cache

added log messages to delete and clear in tokencache

---

ADAL.NET.sln
src/ADAL.PCL/AcquireTokenHandlerBase.cs
src/ADAL.PCL/AcquireTokenOnBehalfHandler.cs
src/ADAL.PCL/AcquireTokenSilentHandler.cs
src/ADAL.PCL/AdalSilentTokenAcquisitionException.cs
src/ADAL.PCL/Constants.cs
tests/Test.ADAL.Common/Sts.cs
tests/Test.ADAL.NET.Unit/AcquireTokenSilentTests.cs
tests/Test.ADAL.NET.Unit/Test.ADAL.NET.Unit.csproj

Added error details to the ADALTokenSilentException. fix for https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/288

add inner exception 

---

src/ADAL.Common/AcquireTokenHandlerBase.cs
src/ADAL.Common/AcquireTokenSilentHandler.cs
src/ADAL.Common/AdalIdHelper.cs
src/ADAL.Common/AdalSilentTokenAcquisitionException.cs
src/ADAL.Common/CommonAssemblyInfo.cs
tests/Test.ADAL.Common/Sts.cs
tests/Test.ADAL.NET.Unit/AcquireTokenSilentTests.cs
tests/Test.ADAL.NET.Unit/Test.ADAL.NET.Unit.csproj

Add inner exception to silentexception

Add inner exception to silentexception

---

src/ADAL.Common/ClientAssertionCertificate.cs

Fix calculation of `x5t` value. Addresses #309.

Fix calculation of `x5t` value. Addresses #309.

---

ADAL.NET.sln
src/ADAL.Common/Constants.cs
src/ADAL.NET.WindowsForms/WindowsFormsWebAuthenticationDialogBase.cs
src/ADAL.WinRT/ADAL.WinRT.csproj
tests/Test.ADAL.Common/AdalTests.cs
tests/Test.ADAL.NET/AdalDotNetTests.cs
tests/Test.ADAL.WinRT.Dashboard/Package.appxmanifest
tests/Test.ADAL.WinRT.Dashboard/Test.ADAL.WinRT.Dashboard.csproj

Pull request for issue v2 #305

Topic v2 issue305new

---

tests/Test.ADAL.Common/Sts.cs
tests/TestApp/TestApp.PCL/TokenBroker.cs

policheck compliance

---

src/ADAL.PCL.Desktop/WindowsFormsWebAuthenticationDialogBase.cs

Issue v3 #306

---

src/ADAL.Common/Logger.cs
src/ADAL.PCL.Android/Logger.cs
src/ADAL.PCL.iOS/Logger.cs
src/ADAL.PCL/ADAL.PCL.csproj
src/ADAL.PCL/IAdalLogCallback.cs
src/ADAL.PCL/LoggerBase.cs
tests/Test.ADAL.NET.Unit/LoggerCallbackTests.cs
tests/Test.ADAL.NET.Unit/Test.ADAL.NET.Unit.csproj

Add logging and callback support for all platforms per Issue #321

Add logging and callback support for all platforms

---

src/ADAL.PCL.iOS/BrokerHelper.cs
src/ADAL.PCL.iOS/BrokerKeyHelper.cs

Remove support for empty broker key as per Issue #318

Remove support for empty broker key

---

src/ADAL.Common/AuthenticationContextIntegratedAuthExtensions.cs
src/ADAL.PCL.CoreCLR/ADAL.PCL.CoreCLR.csproj
src/ADAL.PCL.Desktop/ADAL.PCL.Desktop.csproj
src/ADAL.PCL.iOS/ADAL.PCL.iOS.csproj
src/ADAL.PCL/AuthenticationContext.cs
tests/Test.ADAL.Common/AdalTests.cs
tests/Test.ADAL.Common/AuthenticationContextProxy.cs
tests/Test.ADAL.Common/TokenCacheTests.cs
tests/Test.ADAL.WinRT.Unit/TokenCacheUnitTests.cs
tests/TestApp/AdalDesktopTestApp/Program.cs
tests/TestApp/AdalUniversalTestApp/AdalUniversalTestApp.Windows/MainPage.xaml.cs
tests/TestApp/TestApp.PCL/TokenBroker.cs

Remove non-interactive auth from iOS/Android/WinRT - Issue #320

Remove non-interactive auth from iOS/Android/WinRT

---

src/ADAL.PCL.Desktop/WindowsFormsWebAuthenticationDialogBase.cs

treat about:blank as safe url. Issue #322

treat about:blank as safe url.

---

src/ADAL.PCL.Android/ADAL.PCL.Android.csproj
src/ADAL.PCL/TokenCache.cs
tests/Test.ADAL.Common/TokenCacheTests.cs
tests/Test.ADAL.NET.Unit/TokenCacheUnitTests.cs

Fix cache race condition in v3

---

src/ADAL.PCL.Desktop/ADAL.PCL.Desktop.csproj
src/ADAL.PCL.Desktop/UserPasswordCredential.cs
src/ADAL.PCL.WinRT/ADAL.PCL.WinRT.csproj
src/ADAL.PCL/AcquireTokenNonInteractiveHandler.cs
src/ADAL.PCL/UserCredential.cs
tests/Test.ADAL.Common/AuthenticationContextProxy.cs
tests/Test.ADAL.NET.Unit/NonInteractiveTests.cs
tests/TestApp/AdalDesktopTestApp/Program.cs

Add username/password flow for Desktop only

Add username/password flow for Desktop only

---

src/ADAL.PCL.Desktop/Native/RSACng.cs
tests/Test.ADAL.Common/Sts.cs
tests/TestApp/TestApp.PCL/TokenBroker.cs

policheck cleanup

---

tests/Test.ADAL.Common/Sts.cs

ADAL Code scrubbing and cleanup #356

ADAL Code scrubbing and cleanup #356

---

tests/Test.ADAL.Common/Sts.cs

ADAL Code scrubbing and cleanup #356

ADAL v3 - Code scrubbing and cleanup #356

---

src/ADAL.NET.WindowsForms/ADAL.NET.WindowsForms.csproj
src/ADAL.NET/ADAL.NET.csproj
src/ADAL.WinPhone/ADAL.WinPhone.csproj
src/ADAL.WinPhoneSL/ADAL.WinPhoneSL.csproj
src/ADAL.WinRT/ADAL.WinRT.csproj
tests/Test.ADAL.NET.Friend/Test.ADAL.NET.Friend.csproj
tests/Test.ADAL.NET.Unit/Test.ADAL.NET.Unit.csproj
tests/Test.ADAL.NET.WindowsForms/Test.ADAL.NET.WindowsForms.csproj
tests/Test.ADAL.NET/Test.ADAL.NET.csproj
tests/Test.ADAL.WinPhone.Dashboard/Test.ADAL.WinPhone.Dashboard.csproj
tests/Test.ADAL.WinPhone.Unit/Test.ADAL.WinPhone.Unit.csproj
tests/Test.ADAL.WinPhoneSL.Dashboard/Test.ADAL.WinPhoneSL.Dashboard.csproj
tests/Test.ADAL.WinRT.Dashboard/Test.ADAL.WinRT.Dashboard.csproj
tests/Test.ADAL.WinRT.Unit/Test.ADAL.WinRT.Unit.csproj
tests/Test.ADAL.WinRT/Test.ADAL.WinRT.csproj

update csproj files

---

src/ADAL.PCL.Android/ADAL.PCL.Android.csproj
src/ADAL.PCL.CoreCLR/ADAL.PCL.CoreCLR.csproj
src/ADAL.PCL.Desktop/ADAL.PCL.Desktop.csproj
src/ADAL.PCL.WinPhone/ADAL.PCL.WinPhone.csproj
src/ADAL.PCL.WinRT/ADAL.PCL.WinRT.csproj
src/ADAL.PCL.iOS/ADAL.PCL.iOS.csproj
src/ADAL.PCL/ADAL.PCL.csproj
tests/Test.ADAL.NET.Friend/Test.ADAL.NET.Friend.csproj
tests/Test.ADAL.NET.Unit/Test.ADAL.NET.Unit.csproj
tests/Test.ADAL.NET.WindowsForms/Test.ADAL.NET.WindowsForms.csproj
tests/Test.ADAL.NET/Test.ADAL.NET.csproj
tests/Test.ADAL.WinPhone.Unit/Test.ADAL.WinPhone.Unit.csproj
tests/Test.ADAL.WinRT.Unit/Test.ADAL.WinRT.Unit.csproj
tests/TestApp/AdalAndroidTestApp/AdalAndroidTestApp.csproj
tests/TestApp/AdalDesktopTestApp/AdalDesktopTestApp.csproj
tests/TestApp/AdalUniversalTestApp/AdalUniversalTestApp.Windows/AdalUniversalTestApp.Windows.csproj
tests/TestApp/AdalUniversalTestApp/AdalUniversalTestApp.WindowsPhone/AdalUniversalTestApp.WindowsPhone.csproj
tests/TestApp/AdaliOSTestApp/AdaliOSTestApp.csproj
tests/TestApp/TestApp.PCL/TestApp.PCL.csproj

Adal v4 :- Treat warnings as errors

Adal v4 :- Treat warnings as errors

---

src/ADAL.Common/AcquireTokenNonInteractiveHandler.cs

Enable resource owner grant flow for ADFS in v2 #392

Enable resource owner grant flow for ADFS in v2 #392

---

tests/Test.ADAL.Common/Sts.cs

adalv4:- CredScan clean

---

tests/Test.ADAL.Common/Sts.cs
tests/TestApp/AdalDesktopTestApp/Program.cs

Policheck clean :- ADAL v4

---

src/ADAL.PCL/RequestParameters.cs

Added missing ToString() that caused regressed in GetAuthorizationUrl #412

Added missing ToString() in GetAuthorizationUrl

---

src/ADAL.PCL/RequestParameters.cs

Dev to master merge for release

Dev to master merge for release

---

tests/Test.ADAL.NET.Unit/Test.ADAL.NET.Unit.csproj

remove dead references

---

changelog.txt

pull changelog from master to dev

pull changelog from master to dev

---

src/ADAL.PCL.Android/ADAL.PCL.Android.csproj
tests/Test.ADAL.NET.Unit/UnitTests.cs

build Xamarin Android using 4.3 (Jelly bean)

build Xamarin Android using 4.3 (Jelly bean)

---

contributing.md

[https://cla.msopentech.com/] to [https://cla.microsoft.com/]

fix: Contribution License Agreement site URL (dev branch)

---

src/ADAL.PCL.iOS/WebUI.cs

Invoke on UI thread when running the window controller.

[Mac] Ensure the window controller is run on the UI thread

---

src/ADAL.Common/CommonAssemblyInfo.cs

cleanup assembly info

---

src/ADAL.Common/CommonAssemblyInfo.cs

Update assemblyinfo for build process and semantic versioning.

Update assemblyinfo for build process and semantic versioning.

---

src/ADAL.Common/CommonAssemblyInfo.cs

prepare for release

---

src/ADAL.PCL/AdalHttpClient.cs
src/ADAL.PCL/EncodingHelper.cs
src/ADAL.PCL/HttpClientWrapper.cs
src/ADAL.PCL/HttpWebResponseWrapper.cs
src/ADAL.PCL/IHttpWebResponse.cs
src/ADAL.PCL/MexParser.cs
src/ADAL.PCL/TokenResponse.cs
src/ADAL.PCL/WsTrustRequest.cs
tests/Test.ADAL.NET.Unit/AdalDotNetTests.cs
tests/Test.ADAL.NET.Unit/Mocks/MockHelpers.cs
tests/Test.ADAL.NET.Unit/TestConstants.cs

Returning entire HttpErrorResponse as InnerException to
HttpRequestException

Returning entire HttpErrorResponse as InnerException to HttpRequestException

---

changelog.txt
src/ADAL.Common/CommonAssemblyInfo.cs
src/ADAL.PCL.iOS/BrokerHelper.cs
src/ADAL.PCL.iOS/CryptographyHelper.cs
src/ADAL.PCL.iOS/PlatformParameters.cs

Fix nullpointer exception and set userbroker to false by default. #520

Fix nullpointer exception and set userbroker to false by default. #520

---

README.md
SECURITY-NOTICE.MD

Security Notice Update

---

src/ADAL.PCL.iOS/AuthenticationAgentUINavigationController.cs
src/ADAL.PCL.iOS/PlatformParameters.cs
src/ADAL.PCL.iOS/WebUI.cs

Adds a PreferredStatusBarStyle property to PlatformParameters

---

src/ADAL.Common/CommonAssemblyInfo.cs
src/ADAL.NET.WindowsForms/WindowsFormsWebAuthenticationDialogBase.cs

Porting fixes for #544 and #545 from ADAL v3.

Kpanwar/webview fixes for #544 and #545.

---

src/ADAL.Common/CommonAssemblyInfo.cs

update for next release

---

LICENSE
changelog.txt

Version 3.13.8
=========
This release inclues
- update to nuget package to fix casing of NETStandard.Library nuget dependency
- Add serialization packages to netstandard1.4 target as they are not part of netstandard.

prepare for 3.13.8

---

src/ADAL.PCL.iOS/PlatformParameters.cs
src/ADAL.PCL.iOS/WebUI.cs

Added support for setting transition style on ios #565

ios: added posibility to add/set tranisition style for the login form

---

src/ADAL.PCL/HttpClientWrapper.cs
tests/Test.ADAL.NET.Unit/UnitTests.cs

limit network response size to 1MB.

limit network response size to 1MB.

---

ADAL.NET.sln
samples/DesktopApp/App.config
samples/DesktopApp/DesktopApp.csproj
samples/DesktopApp/Program.cs
samples/DesktopApp/Properties/AssemblyInfo.cs
samples/DesktopApp/obj/Release/DesktopApp.csproj.FileListAbsolute.txt
src/ADAL.Common/AdalException.cs
src/ADAL.Common/Constants.cs
src/ADAL.Common/HttpWebResponseWrapper.cs

limit network response size to 1MB in adal v2

limit network response size to 1MB in adal v2

---

src/ADAL.PCL/AuthenticatorTemplateList.cs

Include Blackforest in trusted authority list in v3

---

automation/AutomationApp/AutomationApp/AuthenticationHelper.cs

The _dev_ branch doesn't build currently due to compilation errors in the _AutomationApp_. This is a minimal change to get the code to compile.

Fix compilation errors in AutomationApp

---

tests/Test.ADAL.NET.Unit/NonInteractiveTests.cs

fix code analysis issues

---

src/ADAL.Common/CommonAssemblyInfo.cs

	fix code analysis issues

---

src/ADAL.PCL.Desktop/DeviceAuthHelper.cs

Fixed an SDL FxCop error I missed in the previous commit

Added missing culture info to string formatting

---

automation/WinFormsAutomationApp/WinFormsAutomationApp.csproj
samples/AdalAndroidTestApp/AdalAndroidTestApp.csproj
samples/AdalCoreCLRTestApp/AdalCoreCLRTestApp.csproj
samples/AdalDesktopTestApp/AdalDesktopTestApp.csproj
samples/AdalUniversalTestApp/AdalUniversalTestApp.Windows/AdalUniversalTestApp.Windows.csproj
samples/AdaliOSTestApp/AdaliOSTestApp.csproj
samples/TestApp.PCL/TestApp.PCL.csproj
samples/XFormsApp.Droid/XFormsApp.Droid.csproj
samples/XFormsApp.iOS/XFormsApp.iOS.csproj
samples/XFormsApp/XFormsApp.csproj
tests/Test.ADAL.NET.Unit/Test.ADAL.NET.Unit.csproj

Explicitly marked all test projects with SonarQubeTestProject=true

---

samples/TestApp.PCL/TokenBroker.cs
src/ADAL.PCL.Android/ADAL.PCL.Android.csproj
src/ADAL.PCL.Android/WebProxyProvider.cs

Miscellaneous: fixed some simple code analysis issues and improved the error message shown in the test app.

Added missing Android Preserve attribute to fix #199584

---

automation/WinFormsAutomationApp/AuthenticationHelper.cs

This enables a common test scenario which has been absent until now.

Automation app can now test login hints.

---

build/LayoutNugetPackage.proj

Added xml files to NuGet layout

---

src/ADAL.PCL.Android/Properties/AssemblyInfo.cs
src/ADAL.PCL.iOS/Properties/AssemblyInfo.cs

https://identitydivision.visualstudio.com/DevEx/_workitems?id=265363

Suppress various FxCop issues (track VSTS 265363)

---

src/Directory.Build.targets

Forgot to incorporate Jean-Marc's comment before checking in.

Updated description in FxCop workaround targets

---

src/ADAL.PCL.iOS/BrokerHelper.cs

Url encode claims for iOS with Broker 

---

sonarqube/adalnet_devcsharp.ruleset

Minor tweak to ruleset

---

src/Microsoft.IdentityModel.Clients.ActiveDirectory/ADAL.WinRT.VS2015.csproj
src/Microsoft.IdentityModel.Clients.ActiveDirectory/Microsoft.IdentityModel.Clients.ActiveDirectory.csproj
src/Microsoft.IdentityModel.Clients.ActiveDirectory/Properties/AssemblyInfo.cs

Create assemblyinfo for both projects because gitversion is not supported for win81. #762

Create assemblyinfo for both projects

---

src/Microsoft.IdentityModel.Clients.ActiveDirectory/Features/NonWinCommon/PromptBehavior.cs
src/Microsoft.IdentityModel.Clients.ActiveDirectory/Features/WinCommon/PromptBehavior.cs
src/Microsoft.IdentityModel.Clients.ActiveDirectory/Internal/OAuthConstants.cs
src/Microsoft.IdentityModel.Clients.ActiveDirectory/Platforms/android/PlatformInformation.cs
src/Microsoft.IdentityModel.Clients.ActiveDirectory/Platforms/iOS/PlatformInformation.cs
src/Microsoft.IdentityModel.Clients.ActiveDirectory/Platforms/net45/PlatformInformation.cs
src/Microsoft.IdentityModel.Clients.ActiveDirectory/Platforms/net45/WebUIFactory.cs
src/Microsoft.IdentityModel.Clients.ActiveDirectory/Platforms/winrt/PlatformInformation.cs
tests/Test.ADAL.NET.Unit/AdalDotNetTests.cs

Add Prompt=select_account support via prompt behavior https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/754

adding select_account prompt

---

src/Microsoft.IdentityModel.Clients.ActiveDirectory/Platforms/net45/WindowsFormsWebAuthenticationDialogBase.cs

Remove URL logging for webview redirects https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/772

removing Url logging for web view redirects

---

changelog.txt

changelog for 3.16.1, per #752

changelog for 3.16.1

---

src/Microsoft.IdentityModel.Clients.ActiveDirectory/AdalClaimChallengeException.cs
src/Microsoft.IdentityModel.Clients.ActiveDirectory/Internal/Http/AdalHttpClient.cs
tests/Test.ADAL.NET.Unit/ClaimsChallengeExceptionTests.cs

Jennyf/claims inner exception 

---

devApps/AdalUniversalTestApp/AdalUniversalTestApp.Windows/MainPage.xaml
devApps/AdalUniversalTestApp/AdalUniversalTestApp.Windows/MainPage.xaml.cs

Add acquire token functionality 

---

automation/WinFormsAutomationApp/AuthenticationHelper.cs

Update to WinFormsAutomationApp to handle claims

---

README.md
changelog.txt

changelog for 3.17.0 and README, per #814

changelog for 3.17.0 and README

---

src/Microsoft.IdentityModel.Clients.ActiveDirectory/Internal/Instance/Authenticator.cs
tests/Test.ADAL.NET.Unit/InstanceDiscoveryTests.cs

~CREATED at Sep 21: This is not yet a formal PR. It is for discussion purpose.~
~UPDATE at Sep 27: There is an alternative implementation in another PR #832. The current PR will probably be closed soon.~
UPDATE at Oct 9: This PR receives new updates. We are now reconsidering it as a qualified candidate.

Authority Migration: Use preferred network to talk to endpoints (by changing endpoints early)

---

tests/Test.ADAL.NET.Integration/FederatedUserCredentialTests.cs
tests/Test.ADAL.NET.Integration/ManagedUsercredentialTests.cs

- fix comments
- modify test names
- add token cache count check
#840 
#852

Minor edits to managed and federated user tests

---

src/Microsoft.IdentityModel.Clients.ActiveDirectory/Internal/Instance/Authenticator.cs
tests/Test.ADAL.NET.Common/Mocks/MockHelpers.cs
tests/Test.ADAL.NET.Common/Mocks/MockHttpMessageHandler.cs
tests/Test.ADAL.NET.Common/TestConstants.cs
tests/Test.ADAL.NET.Integration/AcquireTokenSilentTests.cs
tests/Test.ADAL.NET.Integration/DeviceProfileTests.cs
tests/Test.ADAL.NET.Integration/FederatedUserCredentialTests.cs
tests/Test.ADAL.NET.Integration/ManagedUsercredentialTests.cs
tests/Test.ADAL.NET.Integration/PromptBehaviorTests.cs
tests/Test.ADAL.NET.Unit/AdalDotNetTests.cs
tests/Test.ADAL.NET.Unit/ClaimsChallengeExceptionTests.cs
tests/Test.ADAL.NET.Unit/InstanceDiscoveryTests.cs
tests/Test.ADAL.NET.Unit/NonInteractiveTests.cs
tests/Test.ADAL.NET.Unit/OboFlowTests.cs
tests/Test.ADAL.NET.Unit/Test.ADAL.NET.Unit.csproj
tests/Test.ADAL.NET.Unit/UnitTests.cs

Added URL requirement for MockHttpMessageHandler #847

---

src/Microsoft.IdentityModel.Clients.ActiveDirectory/Platforms/android/BrokerProxy.cs

> ...should be set to
merges with `computedRedirectUri`,  and it's quite confusing in log

Fix ArgumentException message

---

src/Microsoft.IdentityModel.Clients.ActiveDirectory/Internal/Helpers/AdalIdHelper.cs
src/Microsoft.IdentityModel.Clients.ActiveDirectory/Internal/Instance/Authenticator.cs
tests/Test.ADAL.NET.Unit/AdalDotNetTests.cs
tests/Test.ADAL.NET.Unit/UnitTests.cs

Use CultureInvariant in Regex calls

---

appveyor.yml

update per appveyor suggestion to fix android installation

update per appveyor suggestion

---

devApps/AdalAndroidTestApp/AdalAndroidTestApp.csproj
devApps/AdalAndroidTestApp/MainActivity.cs
devApps/AdalAndroidTestApp/UITextView.cs

Added RunOnUiThread call for updates to the UI;

Updated AdalAndroidTestApp to properly update the UI.

---

README.md

Updating the README.md to explain how to use the new Logging mechanismcontrolling if PII is viewed or not (from ADAL 3.18)

Updating the README.md to explain how to use the new Logging mechanism

---

changelog.txt
src/Microsoft.IdentityModel.Clients.ActiveDirectory/Properties/AssemblyInfo.cs

Update version and changelog for hotfix

Update version and changelog for hotfix

---

src/Microsoft.IdentityModel.Clients.ActiveDirectory/AdalSilentTokenAcquisitionException.cs

fixing adal error message for adalv3/dev branch

---

adal/src/Microsoft.IdentityModel.Clients.ActiveDirectory/AdalSilentTokenAcquisitionException.cs

fixing error message for dev branch

---

adal/build/Microsoft.IdentityModel.Clients.ActiveDirectory.nuspec

Fixing #536 in Dev

---

build/Microsoft.IdentityModel.Clients.ActiveDirectory.nuspec

Fixing #536 by changing the vanity URL, since we are not owners of th…e other one)

Fixing #536 by changing the vanity URL

---

adal/build/Microsoft.IdentityModel.Clients.ActiveDirectory.nuspec

Fixing #989 in dev

---

adal/src/Microsoft.IdentityModel.Clients.ActiveDirectory/Features/WinCommon/AdalLogger.cs

#1039 
Customer did a check w/nuget package and AdalEventSource logging now filters based on log level in default log

Filter logs for AdalEventSource based on log level in default log

---

src/Microsoft.IdentityModel.Clients.ActiveDirectory/AuthenticationContext.cs
src/Microsoft.IdentityModel.Clients.ActiveDirectory/Features/WinCommon/Logger.cs
src/Microsoft.IdentityModel.Clients.ActiveDirectory/Properties/AssemblyInfo.cs
tests/Test.ADAL.NET.Common/TestConstants.cs
tests/Test.ADAL.NET.Unit/JsonWebTokenTests.cs

Hotfix #1043

---

changelog.txt
src/Microsoft.IdentityModel.Clients.ActiveDirectory/AuthenticationContext.cs
src/Microsoft.IdentityModel.Clients.ActiveDirectory/Properties/AssemblyInfo.cs
tests/Test.ADAL.NET.Unit/JsonWebTokenTests.cs

Increasing API Surface for Subject Issuer Auth.
https://identitydivision.visualstudio.com/DevEx/_workitems/edit/464258
Verified with manual testing using the dev apps.

Trwalke/adding to x5c surface HOTFIX
