AzureAD/azure-activedirectory-library-for-dotnet

- src/ADAL.PCL.Android/TokenCachePlugin.cs
- src/ADAL.PCL.iOS/TokenCachePlugin.cs
- src/ADAL.PCL/TokenCache.cs
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/166%23discussion_r26719071%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/166%23discussion_r26719583%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/166%23discussion_r26721510%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/166%23discussion_r26722865%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/166%23discussion_r26779832%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/166%23discussion_r26786015%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirecto …
> Persistent cache for both Android and iOS

- src/ADAL.Common/WsTrustRequest.cs
- src/ADAL.NET/UserCredential.cs
- tests/Test.ADAL.NET.Unit/NonInteractiveTests.cs
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/tushargupta51%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/803796%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/209%23issuecomment-114177489%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-06-22T16%3A53%3A30Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/803796%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/tushargupta51%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%2C%20%22Pull%20c73bfab901f740c901e53c8b6976 …
> escape xml chars in password field

- src/ADAL.NET.WindowsForms/SilentWebUI.cs
- src/ADAL.NET.WindowsForms/WebUISettings.cs
Add support to configure silent web ui timeout
<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/212?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/212'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
> Add support to configure silent web ui timeout

- src/ADAL.Common/AcquireTokenNonInteractiveHandler.cs
- src/ADAL.Common/Constants.cs
- src/ADAL.Common/MexParser.cs
- src/ADAL.Common/WsTrustRequest.cs
- src/ADAL.Common/WsTrustResponse.cs
- tests/Test.ADAL.NET.Unit/NonInteractiveTests.cs
- tests/Test.ADAL.NET.Unit/Test.ADAL.NET.Unit.csproj
- tests/Test.ADAL.NET.Unit/TestMex2005.xml
support for WS-Trust 2005
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/223%23discussion_r35997221%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/223%23discussion_r35997813%22%5D%2C%20%22comments%22%3A%20%7B%22Pull%205021a1d4968aa64a1f235a2124fb94efd3b8bc53%20src/ADAL.Common/MexParser.cs%2052%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/223%23discussion_r35997813%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Why%20is%20this%20randomized%3F%22%2C%20%22created_at%22%3A%20%222015-07-31T17%3A51%3A50Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubuserconte …
> support for WS-Trust 2005

- src/ADAL.PCL/AcquireTokenHandlerBase.cs
- src/ADAL.PCL/ProfileInfo.cs
I created a perfectly valid policy in B2C, but did not configure it to send the ‘name’ claim.  Therefore, the profile_info ADAL received from CPIM looks like:
```
{
"ver": "1.0",
"tid": "f494dfc5-cb2f-4d2d-b22b-9e6c68a0d72c",
"sub": null,
"name": null,
"preferred_username": null,
"idp": "facebook.com"
}
```
Which meant that when ADAL populated the UserInfo object, all 4 of its properties had a null value:
```
internal UserInfo(UserInfo other)
{
this.UniqueId = other.UniqueId;
this.DisplayableId = other.DisplayableId;
this.Name = other.Name;
this.Version = other.Version;
}
```
And then in AcquireTokenHandlerBase.LogReturnedToken, ADAL tried to log the UserInfo.UniqueId, which was null: 
PlatformPlugin.Logger.Information(this.CallState,
string.Format(
"=== token Acquisition finished …
> Another small B2C bug fix

- src/ADAL.PCL.Android/ADAL.PCL.Android.csproj
- src/ADAL.PCL.Android/AuthenticationAgentActivity.cs
- src/ADAL.PCL.Android/BrokerConstants.cs
- src/ADAL.PCL.Android/BrokerHelper.cs
- src/ADAL.PCL.Android/Constants.cs
- src/ADAL.PCL.Android/DeviceAuthHelper.cs
- src/ADAL.PCL/AcquireTokenHandlerBase.cs
- src/ADAL.PCL/EncodingHelper.cs
- tests/TestApp/TestApp.PCL/TokenBroker.cs
send pkeyauth header all the time. launch intent for MAM
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/261%23discussion_r42297533%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/261%23discussion_r42298402%22%5D%2C%20%22comments%22%3A%20%7B%22Pull%2083d98e09020c118745e0c9b4293a777738039c9f%20src/ADAL.PCL.Android/AuthenticationAgentActivity.cs%206%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/261%23discussion_r42297533%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22I%20don%27t%20know%20why%20we%20name%20this%20as%20ClientTlsNotSupport%20instead%20of%20PkeyAuthHeader%20or%20something%20 …
> send pkeyauth header all the time. launch intent for MAM

- contributing.md
Was trying to run the tests and they all failed because they are partially signed by default.  I am not sure if this is obvious to everyone so I thought I would add it.
> Adding the fact that you need skip verification enabled to run tests.

- src/ADAL.PCL/AuthenticatorTemplateList.cs
- tests/Test.ADAL.Common/Sts.cs
- tests/Test.ADAL.NET.Unit/UnitTests.cs
Replace the Azure US Gov STS with the actual STS so that requests for that STS do not need to be validated.  Added comments to identify the source of the STS servers.  
NOTE: had to remove 2 spaces in the UT constants to get the UTs to run correctly.  I can submit that separately if needed.
I did not write specific UTs for the Authenticator classes because they would need to be mocked to avoid the web calls and that would require refactoring.
Side note - I was thinking that it might be good to move login.microsoftonline.com to the front of the list since that is most common one these days and the STS team is working to reduce usage of login.windows.net. Would be a VERY minor optimization in the lookup.  Was not sure of possible side effects so I did not do that.
> Adding the US Only STS and comments.

- src/ADAL.Common/AuthenticatorTemplateList.cs
Updating the Azure US Gov STS URL to the US Only STS that has been stood up.  The previous URL was not valid.  Also adding comments about what cloud the STS goes with. 
The same code change has been submitted to the dev branch for inclusion in MAIN.
> Updating the Azure US Gov Cloud STS and adding comments

- src/ADAL.PCL.iOS/BrokerHelper.cs
- src/ADAL.PCL.iOS/PlatformParameters.cs
- src/ADAL.PCL/TokenResponse.cs
- tests/TestApp/AdaliOSTestApp/Info.plist
Xamarin iOS ignored the expires_on claim returned from the broker and used UTC.Now + expires_in to compute expiration time. This resulted in current time as expiration time for the access token.
> Fix bug to consume expires_on claim from iOS broker for Issue #345

- src/ADAL.Common/AcquireTokenHandlerBase.cs
- src/ADAL.Common/AuthenticationResult.cs
- src/ADAL.Common/CacheQueryData.cs
- src/ADAL.Common/CommonAssemblyInfo.cs
- src/ADAL.Common/TokenCache.cs
- src/ADAL.NET/ADAL.NET.csproj
- src/ADAL.NET/AcquireTokenOnBehalfHandler.cs
- src/ADAL.WinPhone/ADAL.WinPhone.csproj
- src/ADAL.WinPhoneSL/ADAL.WinPhoneSL.csproj
- src/ADAL.WinRT/ADAL.WinRT.csproj
- tests/Test.ADAL.Common/TokenCacheTests.cs
- tests/Test.ADAL.NET.Unit/TokenCacheUnitTests.cs
For the server side scenarios, ADAL should check user assertion Hash (if provided) when there are multiple tokens found because the developer did not supply upn. #383
> Check assertion Hash when there are multiple tokens found - v2 #383

- src/ADAL.PCL.Android/BrokerHelper.cs
- src/ADAL.PCL.Android/CryptographyHelper.cs
- src/ADAL.PCL.Android/DeviceAuthHelper.cs
- src/ADAL.PCL.Android/Logger.cs
- src/ADAL.PCL.Android/PlatformInformation.cs
- src/ADAL.PCL.Android/TokenCachePlugin.cs
- src/ADAL.PCL.Android/WebUIFactory.cs
- tests/TestApp/AdalAndroidTestApp/AdalAndroidTestApp.csproj
- tests/TestApp/XFormsApp.Droid/XFormsApp.Droid.csproj
When using ADAL with Xamarin.Android, if full linking is enabled, then
ADAL fails with the following exception:
System.ArgumentNullException: Value cannot be null.
Parameter name: type
at System.Activator.CreateInstance (System.Type type, Boolean nonPublic)
[0x00006] in :0
at System.Activator.CreateInstance (System.Type type) [0x00000] in :0
at
Microsoft.IdentityModel.Clients.ActiveDirectory.PlatformPlugin.InitializeByAssemblyDynamicLinking
() [0x00011] in :0
at Microsoft.IdentityModel.Clients.ActiveDirectory.PlatformPlugin..cctor
() [0x00011] in :0
The problem appears to be that ADAL is dynamically loading types using
reflection, and the linker does not recognize this pattern so removes
them.
Linker attributes could be used to to ensure the dynamically loaded
types are preserved: …
> Add Preseve tag for dynamically loaded classes #385

- src/ADAL.Common/AcquireTokenInteractiveHandler.cs
- src/ADAL.Common/OAuthConstants.cs
ADAL should send haschrome=1 QP for all interactive requests. This will
hide the back button the UI and developers will stop getting
access_denied error when it was actually user_cancel.
> v2 - add haschrome=1 QP to all interactive requests #387

- src/ADAL.PCL/AcquireTokenInteractiveHandler.cs
- src/ADAL.PCL/OAuthConstants.cs
ADAL should send haschrome=1 QP for all interactive requests. This will
hide the back button the UI and developers will stop getting
access_denied error when it was actually user_cancel.
> v3 - add haschrome=1 QP to all interactive requests #387

- src/ADAL.Common/AcquireTokenByRefreshTokenHandler.cs
- src/ADAL.Common/AcquireTokenNonInteractiveHandler.cs
- src/ADAL.Common/CommonAssemblyInfo.cs
- src/ADAL.NET/AuthenticationContext.cs
enable refresh_token grant for ADFS in v2. Remove the check where ADAL failed when authority was not ADFS.
> enable refresh_token grant for ADFS in v2. #402

- src/ADAL.PCL.Desktop/DeviceAuthHelper.cs
- src/ADAL.PCL.Desktop/UserPasswordCredential.cs
- src/ADAL.PCL/EncodingHelper.cs
- src/ADAL.PCL/RequestParameters.cs
- tests/Test.ADAL.Common/AdalTests.cs
- tests/Test.ADAL.NET.Friend/RecorderHttpClient.cs
- tests/Test.ADAL.NET.Friend/RecorderSettings.cs
- tests/Test.ADAL.NET.Friend/RecorderWebUI.cs
- tests/Test.ADAL.NET.Unit/UnitTests.cs
- tests/Test.ADAL.WinRT.Unit/ReplayerHttpClient.cs
- tests/TestApp/TestApp.PCL/TokenBroker.cs
Fix array resize issue during Url encoding where Array.Resize call was
not being provided new size of the array and developer got index out of
bound exception. #406
> Fix array resize issue during Url encoding

- contributing.md
[https://cla.msopentech.com/] to [https://cla.microsoft.com/]
> fix: Contribution License Agreement site URL (servicing branch)

- tests/TestApp/AdalMacTestApp/ViewController.cs
This PR is just to fix a couple errors in the AdalMacTestApp.
The constructor that takes the second parameter was removed in this commit: https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/commit/16268d05889f3c8a8b0883fc3ed98ce214793913
The `UseModalDialog` property was removed in this commit: https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/commit/02ba9c3ceb754b6caf49a4a5c203a6dfcce44737
/cc @mhutch
> Fix Mac test app

- src/ADAL.PCL.Desktop/CryptographyHelper.cs
We should only up-level software keys using the CAPI PROV_RSA_FULL and
PROV_RSA_SCHANNEL providers and never up-level hardware based keys.
> Fix to allow hardware based keys to perform authentication.

- src/ADAL.Common/CommonAssemblyInfo.cs
- src/ADAL.NET/CryptographyHelper.cs
We should only up-level software keys using the CAPI PROV_RSA_FULL and
PROV_RSA_SCHANNEL providers and never up-level hardware based keys.
>  Fix to allow hardware based keys to perform authentication.

- src/ADAL.PCL/AcquireTokenNonInteractiveHandler.cs
- tests/Test.ADAL.NET.Unit/AdalDotNetTests.cs
- tests/Test.ADAL.NET.Unit/Mocks/MockHelpers.cs
per #460, set displayableId as the username for cache lookup. This will
make sure that when user2 creds are passed to the API, it does not
return the token for user1.
> set displayableId as the username for cache lookup

- src/ADAL.PCL.Mac/ADAL.PCL.Mac.csproj
This simply changes the target framework to Xamarin.Mac .NET 4.5 target.
> Change Mac library to use Xamarin.Mac .NET 4.5 profile.

- src/ADAL.PCL.Android/BrokerProxy.cs
- src/ADAL.PCL/AdalHttpClient.cs
In Android API 15 and under, adal could communicate with a fake broker app where 
the attacker could take the certificate from a valid broker app and create a
fake certificate chain since the lower sdk do not perform certificate
chain validation.
The fix will create a certificate chain based on the returned signatures
from the os, and validate the certificate chain.
> verify certificate chain for broker app

- src/ADAL.PCL/AcquireTokenHandlerBase.cs
- src/ADAL.PCL/AcquireTokenNonInteractiveHandler.cs
- src/ADAL.PCL/AcquireTokenOnBehalfHandler.cs
- tests/Test.ADAL.Common/TokenCacheTests.cs
- tests/Test.ADAL.NET.Unit/TokenCacheUnitTests.cs
Unexpected multiple_matching_tokens_detected even when User has been
provided. The problem occurs because AcquireTokenHandlerBase initializes
CacheQueryData in its constructor and it uses fields such as
this.UniqueId and this.DisplayableId that have not been initialized yet.
They get initialized by subclasses such as AcquireTokenSilentHandler or
AcquireTokenInteractiveHandler after the base class constructor exits.
> Unexpected multiple_matching_tokens_detected

- src/ADAL.PCL.Android/AuthenticationAgentContinuationHelper.cs
- src/ADAL.PCL.Android/WebUI.cs
AuthenticationAgentContinuationHelper throws null pointer exception when
there is no ADAL call pending. ADAL should check if there is a call
pending, then only save the response from activity result. #490
> OnResume throws nullpointerexception in client app

- src/ADAL.PCL/AuthenticationContext.cs
- src/ADAL.PCL/AuthenticationResult.cs
- src/ADAL.PCL/AuthenticationResultEx.cs
- src/ADAL.PCL/TokenCache.cs
- src/ADAL.PCL/UserAssertion.cs
- src/ADAL.PCL/UserInfo.cs
- tests/Test.ADAL.Common/TokenCacheTests.cs
- tests/Test.ADAL.NET.Unit/AdalDotNetTests.cs
AuthenticationContext.AcquireTokenAsync() occasionally returns null
access token from cache per #487
This PR also includes fix for https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/493
> AcquireTokenAsync returns null access token

- src/ADAL.Common/CommonAssemblyInfo.cs
- src/ADAL.PCL.Desktop/ADAL.PCL.Desktop.csproj
- src/ADAL.PCL.Desktop/CryptographyHelper.cs
- src/ADAL.PCL.Desktop/SecureClientSecret.cs
- src/ADAL.PCL.Desktop/UserPasswordCredential.cs
- src/ADAL.PCL/ADAL.PCL.csproj
- src/ADAL.PCL/AcquireTokenHandlerBase.cs
- src/ADAL.PCL/AdalHttpClient.cs
- src/ADAL.PCL/ClientCredential.cs
- src/ADAL.PCL/ClientKey.cs
- src/ADAL.PCL/HttpMessageHandlerFactory.cs
- src/ADAL.PCL/ISecureClientSecret.cs
- tests/Test.ADAL.NET.Unit/AdalDotNetTests.cs
- tests/Test.ADAL.NET.Unit/UnitTests.cs
Added support for SecureString as client secret per #470.
Fixed SecureString.Clear issue where ADAL was not checking if string was
readonly per #458.
Client Resiliency did no retry on connection timeouts.
> Support SecureString for client secrets

- src/ADAL.Common/AcquireTokenHandlerBase.cs
- src/ADAL.Common/CommonAssemblyInfo.cs
- tests/Test.ADAL.NET.Unit/AcquireTokenSilentTests.cs
- tests/Test.ADAL.NET.Unit/NonInteractiveTests.cs
- tests/Test.ADAL.NET/AdalDotNetTests.cs
- tests/Test.ADAL.NET/AuthenticationContextProxy.cs
Per issue #499.
When using a call pattern like this:
UserCredential credential = new UserCredential(userId, password);
result = context.AcquireToken(config.ResourceClientUri, config.ClientId, credential);
If the token cache contains a token with the same Authority, Resource, and ClientId, but a different UserId, that token is incorrectly returned.
> UserCredential.Username is not used for cache lookups.

- src/ADAL.PCL/AcquireTokenByDeviceCodeHandler.cs
- src/ADAL.PCL/AuthenticationContext.cs
- tests/Test.ADAL.NET.Unit/DeviceCodeFlowTests.cs
- tests/Test.ADAL.NET.Unit/Test.ADAL.NET.Unit.csproj
per #500, The Device authentication flow will always throw a null reference exception when attempting to acquire a token by device code. This is because the constructor for AcquireTokenHandlerBase uses requestData.ClientKey and requestData.Resource, and they are not initialized when it is called.
> Null reference exception in Device authentication flow.

- src/ADAL.PCL/UserInfo.cs
In CoreCLR 1.0.4 Json serialization, it is required for constructors of serialized types to be visible to the serializer.  This causes exceptions when running in CoreCLR 1.0.4
> Update UserInfo class for CoreCLR 1.0.4 issues

- src/ADAL.Common/CommonAssemblyInfo.cs
- src/ADAL.PCL/AcquireTokenHandlerBase.cs
- src/ADAL.PCL/AcquireTokenOnBehalfHandler.cs
- src/ADAL.PCL/TokenCache.cs
- tests/Test.ADAL.NET.Unit/AcquireTokenSilentTests.cs
- tests/Test.ADAL.NET.Unit/OboFlowTests.cs
- tests/Test.ADAL.NET.Unit/Test.ADAL.NET.Unit.csproj
add extensive OBO test coverage and add the check to always match on user assertion when provided instead of relying on cache entry. this is because the developer may pass an updated assertion with new claims like MFA etc.
> OBO test coverage and user assertion logic update

- src/ADAL.PCL.WinRT/WebUI.cs
The problem originates in WebUI.ProcessAuthorizationResult (from src\ADAL.PCL.WinRT\WebUI.cs). In the event that the system returns WebAuthenticationStatus.ErrorHttp, it creates an AuthorizationResult with the returned HTTP status code in the returnedUriInput field.
case WebAuthenticationStatus.ErrorHttp:
result = new AuthorizationResult(AuthorizationStatus.ErrorHttp, webAuthenticationResult.ResponseErrorDetail.ToString(CultureInfo.CurrentCulture));
However, the AuthorizationResult c’tor (in src\ADAL.PCL\AuthorizationResult.cs) only has special handling for the UserCancel and UnknownError result statuses. So, ErrorHttp results are passed off to the ParseAuthorizeResponse method which tries parsing the returnedUriInput as a Uri and throws. This exception isn’t being wrapped up in an …
> UWP fails when handling WebAuthenticationStatus.ErrorHttp 

- src/ADAL.PCL.Desktop/WindowsFormsWebAuthenticationDialogBase.cs
The javascript code is getting accounted as non https url in ADAL.
> Fix for :- Exception in ADAL webview on EvoSTS consent screen

- src/ADAL.Common/CommonAssemblyInfo.cs
- src/ADAL.NET.WindowsForms/WindowsFormsWebAuthenticationDialogBase.cs
Ignore all navigation events once redirect_uri is reached in the webview  per #573
>  Ignore all navigation events once redirect_uri is reached in the webview

- README.md
These got removed in a subsequent merge after the original update.
> Restore sample/doc links to readme.md

- samples/TestApp.PCL/TestApp.PCL.csproj
- samples/XFormsApp.Droid/XFormsApp.Droid.csproj
- samples/XFormsApp.iOS/XFormsApp.iOS.csproj
- samples/XFormsApp/XFormsApp.csproj
- src/ADAL.PCL/IAdalLogCallback.cs
This commit fixes some but not all of the build issues in the _dev_ branch.
@kpanwar FYI the _automation\AutomationApp_ and _automation\AutomationApp.UWP_ projects don't currently build on a clean machine.
It doesn't look there is currently a CI build running against the _dev_ branch, only against _master_, which is why these breaks weren't caught sooner. I have a VSTS build definition targeting the _dev_ branch that I'll set up as a CI build once we've sorted out the permissions to set up the GitHub hooks.
> Fix build breaks in samples and release builds

- tests/Test.ADAL.Common/TokenCacheTests.cs
- tests/Test.ADAL.NET.Unit/AcquireTokenSilentTests.cs
- tests/Test.ADAL.NET.Unit/AdalDotNetTests.cs
- tests/Test.ADAL.NET.Unit/AuthenticationParametersTests.cs
- tests/Test.ADAL.NET.Unit/Common/AssertException.cs
- tests/Test.ADAL.NET.Unit/DeviceCodeFlowTests.cs
- tests/Test.ADAL.NET.Unit/NonInteractiveTests.cs
- tests/Test.ADAL.NET.Unit/Test.ADAL.NET.Unit.csproj
- tests/Test.ADAL.NET.Unit/UnitTests.cs
Added a helper method to check that the expected exceptions are being thrown and modified all of the tests to use the new helper (for consistency, I've changed all of the tests, including those that were correctly implemented before)
Using the helper method is simpler and less error-prone; previously
some of the tests were not correctly checking for error and could have
been passing even if the expected exception was not thrown.
There are two cases in AuthenticationParametersTests where this is
happening (issue #611)
> Modified exception checking in tests

- src/ADAL.PCL/Http/HttpMessageHandlerFactory.cs
This is a useful change for enterprises who want to connect from their app to Azure AD from an internal network via proxy.  This is especially useful for Xamarin.Android applications since proxy settings on android usually only apply to the web browser/web-views but not HTTP calls from within 3rd party applications.  For some developers, specifying a proxy programmatically is the only answer for many scenarios and with this change, the ADAL http requests will respect the DefaultWebProxy that is set for that app.
> Added support for using the default IWebProxy inside ADAL.

- src/ADAL.PCL/Authority/AuthenticatorTemplateList.cs
Adding the new STS for Azure Gov (login.microsoftonline.us). Leaving the previous URL in place for compatibility. We can remove as we wind down support in 12 to 18 months.
> Add new US Gov STS

- build/ADAL.CodeCoverage.runsettings
Added a test runsettings file that excludes test assemblies and test apps from the code coverage results.
By default, code coverage is calculated on all the projects in the solution. This gives a misleading coverage number: including the sample apps pushes the coverage number down since none of the code is executed, and including the test projects tends to push the coverage number up (tests don't tend to include much branching code so most of the code is executed most of the time).
> Added run settings file to exclude test projects from code coverage

- src/ADAL.PCL.WinRT/DeviceAuthHelper.cs
See https://github.com/dotnet/roslyn/pull/16834 - the Roslyn compiler wasn't correctly parsing >>
> Workaround for new Roslyn bug that prevented compilation in VS2017

- automation/WinFormsAutomationApp/AuthenticationHelper.cs
- automation/WinFormsAutomationApp/WinFormsAutomationApp.csproj
- automation/WinFormsAutomationApp/packages.config
Replace `JavaScriptSerializer` with JSON.NET, at least for the device code flows, in the WinForms automation test app. The way JSS serialises dates is not compliant with ISO 8601.
Change the test app to return UTC dates formatted in ISO 8601 format.
OSS Usage Request ID is 32438.
> Use JSON.NET in automation test app (device code)

- src/ADAL.PCL.iOS/BrokerHelper.cs
We had some exceptions while trying to silently login with an expired refresh token because `BrokerHelper.CanInvokeBroker` does not null-check `pp`.
> Check PlatformParameters in BrokerHelper.CanInvokeBroker for null

- src/ADAL.PCL/Flows/NonInteractive/WsTrustRequest.cs
- tests/Test.ADAL.NET.Unit/NonInteractiveTests.cs
Modified the unit test to validate the generated XML against the schema.
This uncovered a second error in the _ws-trust_ schema namespace.
> Fixed SOAP XML errors. Bug #401

- changelog.txt
- src/ADAL.Common/CommonAssemblyInfo.cs
Bump the assembly version number to 3.14.0 and update _changelog.txt_ with appropriate details.
I also noticed that the changelog had not been updated for the 3.13.9 release so I copied the notes from that GitHub release.
> Bump version number to 3.14

- src/ADAL.PCL.Android/DeviceAuthHelper.cs
- src/ADAL.PCL/Flows/NonInteractive/WsTrustRequest.cs
Fix two instances reported by the SDL FxCop task
> Adding missing culture info to string format operations

- src/ADAL.PCL.Desktop/ADAL.PCL.Desktop.csproj
- src/ADAL.PCL.WinRT/ADAL.PCL.WinRT.csproj
- src/ADAL.PCL.iOS/ADAL.PCL.iOS.csproj
The SDL code analysis checks are now being carried out in the VSTS ADAL.Net CI build using the internal SDL task.
> Removed references to internal code analysis ruleset

- build/credscan-exclusion.json
- tests/Test.ADAL.Common/Sts.cs
Added cred scan exclusions for test certificates.
Changed the test code to remove a false-positive password detected by CredScan.
I've added a VSTS work item (190589) to review the exclusions to see if they can be avoided.
> Added CredScan exclusions

- automation/WinFormsAutomationApp/Program.cs
Force kill any other running WinFormsAutomationApp instances when starting a new one.
When running E2E tests this allows us ensure that the WinAppDriver is controlling the correct instance and not a stale instance from a previous test run which didn't finish gracefully.
> Automatically kill other WinFormsAutoApp on start

- automation/WinFormsAutomationApp/DeleteCookies.cs
In the _WinFormsAutomationApp_, use `System.Runtime.InteropServices.ComTypes.FILETIME` over `System.Runtime.InteropServices.FILETIME` as per the obsolete warning suggestion.
See VSTS PRs for update to the 'headless' copy.
> Fix warnings about FILETIME struct use

- src/ADAL.PCL/AuthenticationParameters.cs
- src/ADAL.PCL/Utilities/EncodingHelper.cs
- tests/Test.ADAL.NET.Unit/UnitTests.cs
Throw exception when the authorisation header contains a malformed key-value pair string which isn't in the format: "X=Y" or "X".
I.e., "X=Y=Z" is now invalid.
> Fix #611: implement stricter auth header parsing

- src/ADAL.PCL/Cache/TokenCacheKey.cs
- src/ADAL.PCL/TokenCache.cs
- tests/Test.ADAL.NET.Unit/Test.ADAL.NET.Unit.csproj
- tests/Test.ADAL.NET.Unit/TokenCacheKeyTests.cs
Change `TokenCacheKey.GetHashCode` to ensure that:
1. the result is *not* dependent on the current thread's culture,
1. the result is *not* dependent on mutable properties.
> Fix #717: Make TokenCacheKey.GetHashCode not culture dependent

- src/ADAL.PCL/Platform/LoggerBase.cs
Explicitly use the ISO 8601 format for date/times when generating log messages. Also ensure we're using the Invariant Culture when constructing the final string (we're only using string.Format here to do concatenation).
This should hopefully also fix issue #710.
> Use ISO 8601 format for logger timestamps

- tests/Test.ADAL.NET.Unit/TokenCacheKeyTests.cs
The Jenkins build agent (and other possible machines) does not have the required set-up to switch to the Turkish culture. Assert inconclusive in this case.
> Assert inconclusive if culture not found in tests

- src/ADAL.PCL.Desktop/CryptographyHelper.cs
The default RSA implementation has changed in .NET Framework 4.7.
Previously we got handed back a instance of `RSACryptoServiceProvider`, whereas now we get a type of `RSACng`.
Because we're targeting .NET Framework 4.5 and `RSACng` was only introduced in .NET Framework 4.6, we cannot actually call methods on that type (without using reflection anyway..).
Instead we now try and construct and initialise an new instance of `RSACryptoServiceProvider` using the private key parameters in the X509 certificate.
> Fix #708: Handle new RSA default (RSACng) on netfx4.7

- src/ADAL.PCL.Android/BrokerProxy.cs
- src/ADAL.PCL.WinRT/DeviceAuthHelper.cs
- src/ADAL.PCL.iOS/BrokerHelper.cs
There are some more FxCop violations regarding globalisation rules (use of string methods without explicit regard for culture) present in the WinRT, iOS, and Android platform assemblies.
Correcting the issues in this PR.
> Address some globalisation issues in WinRT, iOS and Android platform assemblies

- src/Directory.Build.targets
The VSTS FxCop task can't realistically be used to analyse .Net Core projects because there isn't a way to configure it to find all of the assemblies referenced through NuGet. We could manually supply the full path to each assembly, but that is error-prone and fragile.
This task works round the problem by copy all of the referenced assemblies by a project to a single folder, which the SDL task can then be configured to search.
See the comments in the new file for more information.
> Workaround for passing assembly references to VSTS FxCop task

- src/ADAL.PCL/AuthenticationContext.cs
- src/ADAL.PCL/Http/AdalHttpClient.cs
- tests/Test.ADAL.NET.Unit/AdalDotNetTests.cs
#740 Add unit tests for GetAuthReqeustUrlAsync without claims overload
> #740 - Fix api surface - Add GetAuthRequestUrlAsync method without claims overload 

- src/ADAL.PCL.Android/CryptographyHelper.cs
- src/ADAL.PCL.WinRT/CryptographyHelper.cs
- src/ADAL.PCL.iOS/CryptographyHelper.cs
In `AcquireTokenHandlerBase.cs` line 355, the following line appears:
`result.UserInfo != null
? PlatformPlugin.CryptographyHelper.CreateSha256Hash(result.UserInfo.UniqueId)
: "null"`
When the token is first returned from the server, the UserInfo object is null and `CreateSha256Hash()` is not called. However, on subsequent returns the UserInfo object is no longer null, but it is empty (`result.UserInfo.UniqueId == null`). Thus `CreateSha256Hash()` is called with a null argument whenever a token is returned from cache.
`CreateSha256Hash()` is a platform-specific method which is implemented in `CryptographyHelper.cs`. The Desktop, CoreCLR and iOS platform libraries have defensive coding that checks for null strings, but the WinRT and Android libraries do not. Most of the other methods in …
> Fixed WinRT failure when logging an empty UserInfo object.

- appveyor.vs2015.yml
- src/Microsoft.IdentityModel.Clients.ActiveDirectory/AuthenticationContext.cs
- src/Microsoft.IdentityModel.Clients.ActiveDirectory/Features/WinCommon/AuthenticationContextConfidentialClientExtensions.cs
- tests/Test.ADAL.NET.Integration/Test.ADAL.NET.Integration.csproj
- tests/Test.ADAL.NET.Integration/packages.config
Remove Confidential Client API surface from iOS/Android. per #759
> Remove Confidential Client API surface from iOS/Android

- src/Microsoft.IdentityModel.Clients.ActiveDirectory/AdalClaimChallengeException.cs
- src/Microsoft.IdentityModel.Clients.ActiveDirectory/AuthenticationContext.cs
- src/Microsoft.IdentityModel.Clients.ActiveDirectory/Features/WinCommon/AuthenticationContextConfidentialClientExtensions.cs
- src/Microsoft.IdentityModel.Clients.ActiveDirectory/Platforms/android/AuthenticationAgentContinuationHelper.cs
- src/Microsoft.IdentityModel.Clients.ActiveDirectory/Platforms/android/PlatformParameters.cs
- src/Microsoft.IdentityModel.Clients.ActiveDirectory/Platforms/iOS/AuthenticationContinuationHelper.cs
- src/Microsoft.IdentityModel.Clients.ActiveDirectory/Platforms/iOS/PlatformParameters.cs
- src/Microsoft.IdentityModel.Clients.ActiveDirectory/Properties/InternalsVisibleTo.cs
ADAL Should Use [assembly: CLSCompliant(true)] and only set to false where it is needed. per #673
> ADAL Should Use [assembly: CLSCompliant(true)]

- automation/WinFormsAutomationApp/AuthenticationHelper.cs
Example implementation on Objective C, which matches the snake_case system seen in all other values:
https://github.com/AzureAD/azure-activedirectory-library-for-objc/blob/61e6a751fe390f2cf4cab64e17c84a6139378042/ADAL/ADALAutomation/ADAutoMainViewController.m#L158
As `UserIdentifierType.TryParse(...)` was expecting `"OptionalDisplayableId"`, `"optional_displayable"` wasn't being recognised. Because C#'s enum parsing is pretty bad, I'm just using some if/then statements with `string.Equals(...)` calls. We could also have tried platform-specific strings, but this way seems neater.
> Fixed automation app not parsing snake_cased user_identifier_type.

- src/Microsoft.IdentityModel.Clients.ActiveDirectory/ClientCredential.cs
- src/Microsoft.IdentityModel.Clients.ActiveDirectory/Features/WinCommon/AuthenticationContextConfidentialClientExtensions.cs
There are scnearios for Kiosk mode in WinRT that requires the client app to execute client credentials grant. This means WinRT binary should only expose API for client credential and not the ones that redeem authcode or pass in user assertion. We will only support client secret for now, until there is an explicit need to support certificates. #768
> only expose client credentials with client secret on winRT

- src/Microsoft.IdentityModel.Clients.ActiveDirectory/AdalServiceException.cs
- src/Microsoft.IdentityModel.Clients.ActiveDirectory/AuthenticationParameters.cs
- src/Microsoft.IdentityModel.Clients.ActiveDirectory/Internal/Http/AdalHttpClient.cs
- src/Microsoft.IdentityModel.Clients.ActiveDirectory/Internal/Http/HttpClientWrapper.cs
- src/Microsoft.IdentityModel.Clients.ActiveDirectory/Internal/Http/HttpWebResponseWrapper.cs
- src/Microsoft.IdentityModel.Clients.ActiveDirectory/Internal/Http/IHttpWebResponse.cs
- tests/Test.ADAL.NET.Unit/AdalDotNetTests.cs
- tests/Test.ADAL.NET.Unit/Mocks/MockHelpers.cs
Added HttpResponseHeaders to the AdalServiceException that contains all headers returned in the web response. #721
> Trwalke/retry after header #721

- src/Microsoft.IdentityModel.Clients.ActiveDirectory/Platforms/iOS/BrokerHelper.cs
- src/Microsoft.IdentityModel.Clients.ActiveDirectory/Platforms/iOS/PlatformParameters.cs
- src/Microsoft.IdentityModel.Clients.ActiveDirectory/Platforms/iOS/WebUI.cs
dereference UIViewController instances in Xamarin.iOS upon completion of the request. not doing so causes the OS to retain the object and causes memory leak, per #534
> dereference UIViewController for iOS

- build/prepare-versioning.ps1
- src/ADAL.Common/CommonAssemblyInfo.cs
- src/ADAL.PCL.Desktop/CryptographyHelper.cs
- src/ADAL.PCL.Desktop/DeviceAuthHelper.cs
This PR includes fix to use RSACng instead of RSACSP in case of  .net 4.7. Existing code was attempting to export private key and create RSA CSP from it. This would fail if the key is marked as non-exportable, per #752
The CI builds will fail as they expect multi-target project configuration. Internal build system will still be able to create a successful build
> Fix to use RSACng when RSA CSP is not resolved

- src/Microsoft.IdentityModel.Clients.ActiveDirectory/Platforms/net45/CryptographyHelper.cs
- src/Microsoft.IdentityModel.Clients.ActiveDirectory/Platforms/net45/DeviceAuthHelper.cs
Port net47 fix from 3.16.1 to 3.17.0 https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/781
> use RSACng instead of RSACSP in case of .net 4.7

- build/LayoutNugetPackage.proj
- src/Microsoft.IdentityModel.Clients.ActiveDirectory/ADAL.WinRT.VS2015.csproj
Current netcore45 binaries are not getting published in the nuget. This PR updates the build scripts to include the binaries correctly. per #792
> Enable netcore45 for nuget packaging

- src/Microsoft.IdentityModel.Clients.ActiveDirectory/AuthenticationContext.cs
Hide Device Profile API for iOS/Android because it should only be used in desktop, net core and UWP (for IoT), per #806
> hide device profile API on iOS and Android

- src/Microsoft.IdentityModel.Clients.ActiveDirectory/AuthenticationContext.cs
- src/Microsoft.IdentityModel.Clients.ActiveDirectory/Features/WinCommon/AuthenticationContextConfidentialClientExtensions.cs
- src/Microsoft.IdentityModel.Clients.ActiveDirectory/Internal/EncodingHelper.cs
Hide GetAuthorizationRequestUrl() API from WinRT, iOS and Android as this API is only relevant for confidential client use in net45 and net core., per #808
> Hide GetAuthorizationRequestUrl() API from WinRT, iOS and Android

- src/Microsoft.IdentityModel.Clients.ActiveDirectory/AuthenticationResult.cs
- src/Microsoft.IdentityModel.Clients.ActiveDirectory/Internal/Flows/AcquireTokenByAuthorizationCodeHandler.cs
- src/Microsoft.IdentityModel.Clients.ActiveDirectory/Internal/Flows/AcquireTokenHandlerBase.cs
- src/Microsoft.IdentityModel.Clients.ActiveDirectory/Internal/Flows/AcquireTokenInteractiveHandler.cs
- src/Microsoft.IdentityModel.Clients.ActiveDirectory/Internal/Instance/TokenResponse.cs
- src/Microsoft.IdentityModel.Clients.ActiveDirectory/Platforms/android/BrokerHelper.cs
- tests/Test.ADAL.NET.Integration/DeviceProfileTests.cs
- tests/Test.ADAL.NET.Integration/SovereignCloudsTests.cs
- tests/Test.ADAL.NET.Unit/Mocks/MockHelpers.cs
- tests/Test.ADAL.NET.Unit/UnitTests.cs
disable sovereign cloud feature for 3.17.0 because some services are not ready for a full end to end validation.
> disable sovereign cloud feature

- src/Microsoft.IdentityModel.Clients.ActiveDirectory/Platforms/net45/WebBrowserNavigateErrorEventArgs.cs
The documentation XML file inside the package is lacking the summary for one of the types (WebBrowserNavigateErrorEventArgs) - this causes the type description to be rendered blank on docs.microsoft.com. per #797
> updated the documentation header for WebBrowserNavigateErrorEventArgs

- devApps/XFormsApp/SecondPage.cs
- src/Microsoft.IdentityModel.Clients.ActiveDirectory/Platforms/android/BrokerHelper.cs
- src/Microsoft.IdentityModel.Clients.ActiveDirectory/Platforms/android/BrokerProxy.cs
- src/Microsoft.IdentityModel.Clients.ActiveDirectory/Platforms/iOS/BrokerHelper.cs
- src/Microsoft.IdentityModel.Clients.ActiveDirectory/Platforms/iOS/PlatformParameters.cs
- src/Microsoft.IdentityModel.Clients.ActiveDirectory/Platforms/iOS/WebUI.cs
- adding scrollable log section to XFormsApp
- adding padding to IOS XFormsApp to keep all ui elements visible
- fixing CallerViewController Null pointer exception for IOS platform,
It is related to recent fix for "memory leaks on IOS"
Since PlatformParameter instance might an probably should be used across few AcquireToken calls, and because AcquireToken methods do not  own it (PlatformParameter created and owned by outer to AcquireToken method code )  It should not be changed inside  AcquireToken calls 
- fix for null pointer exception on Android while calling CanSwitchToBroker
- fix for applying SupportToAddUserThroughBroker logic to Company Portal broker
> fixes for Android and IOS platforms

- tests/Test.ADAL.NET.Integration/AcquireTokenSilentTests.cs
Created a test case where cache is empty. ADAL should return error.
Created a test case where a expired access token and a invalid refresh token exist in cache.
#826
> Created a test case where cache is empty. ADAL should return error.

- tests/Test.ADAL.NET.Integration/ManagedUsercredentialTests.cs
Test case where valid access token already exists in cache. this should result in cache token returned back.
Test case where valid access token for user1 already exists in cache. API is called for user2 and in this case network call is made to user realm endpoint and then to token endpoint to get token from AAD. Now the cache should have 2 entries.
Test case with expired access token and valid refresh token in cache. This should result in refresh token being used to get new AT instead of user creds.
Test case where user realm discovery fails because user does not exist in AAD.
Test case where user realm discovery cannot determine the user type
#840
VSTS 292990
> Ensure Managed User Credentials integration tests exist in ADAL.NET PR

- automation/WinFormsAutomationApp/AuthenticationHelper.cs
- src/Microsoft.IdentityModel.Clients.ActiveDirectory/Internal/Flows/AcquireTokenHandlerBase.cs
- src/Microsoft.IdentityModel.Clients.ActiveDirectory/TokenCache.cs
- tests/Test.ADAL.NET.Unit/InstanceDiscoveryTests.cs
- tests/Test.ADAL.NET.Unit/TokenCacheTests.cs
- tests/Test.ADAL.NET.Unit/TokenCacheUnitTests.cs
Functionality:
* Use the preferred_cache, given host, and aliases from the Authority validation cache to look up tokens in the token cache
* Use the preferred_cache when writing tokens into cache
Difference between | PR #816 | This PR
--- | ------- | --------
Functionality | See above | Same
Implemented in | class AcquireTokenHandlerBase | class TokenCache
Files changed | 2 | 7 (Because the `LoadFromCache()` and `StoreToCache()` become async methods now, we do need to adjust all pre-existing test cases 
Pick the one you like to review. Once merged, we will close the other PR.
> Authority Migration: TokenCache read/write changes (implemented inside TokenCache class)

- src/Microsoft.IdentityModel.Clients.ActiveDirectory/Internal/Instance/Authenticator.cs
- src/Microsoft.IdentityModel.Clients.ActiveDirectory/Internal/Instance/InstanceDiscovery.cs
- src/Microsoft.IdentityModel.Clients.ActiveDirectory/TokenCache.cs
This is exactly the same issue mentioned in
[this StackOverflow question](https://stackoverflow.com/questions/32076823/string-interpolation-in-visual-studio-2015-and-iformatprovider-ca1305).
Since we are not targeting framework 4.6 yet, we will have to switch back
to the old school string.Format(...)
> Replace string interpolation with old school string.Format(...)

- tests/Test.ADAL.NET.Common/Mocks/MockHelpers.cs
- tests/Test.ADAL.NET.Integration/FederatedUserCredentialTests.cs
- tests/Test.ADAL.NET.Integration/ManagedUsercredentialTests.cs
- tests/Test.ADAL.NET.Integration/PromptBehaviorTests.cs
- tests/Test.ADAL.NET.Unit/InstanceDiscoveryTests.cs
- tests/Test.ADAL.NET.Unit/OboFlowTests.cs
While this PR is triggered by the modification for the default Instance Discovery mock, the actual adjustment to those affected test cases (some of them are 1 year old) is orthogonal to the Instance Discovery feature, and rightfully so. In fact, after those test cases refactor, they would pass no matter the default Instance Discovery mock contain Authority Migration metadata or not.
> Refactor pre-existing test cases to reduce dependency

- contributing.md
Updating the contribution guide (contributing.md) to explain:
- how to clone/fork to avoid long names issues, 
- how to restore the nuget packages
See #895
> Updating the contribution guide (contributing.md)

- tests/Test.ADAL.NET.Common/Test.ADAL.NET.Common.csproj
- tests/Test.ADAL.NET.Integration/Test.ADAL.NET.Integration.csproj
- tests/Test.ADAL.NET.Unit/Test.ADAL.NET.Unit.csproj
Fixing #918  (tests don't show-up in the Test Explorer in VS2017.4+)
by upgrading the NuGet packages for the test adapter and test framework.
See minimum version requirements (https://docs.microsoft.com/en-us/visualstudio/test/live-unit-testing-faq#what-test-frameworks-does-live-unit-testing-support-and-what-are-the-minimum-supported-versions)
> Fixing #918  (tests don't show-up in the Test Explorer in VS2017.4+)

- src/Microsoft.IdentityModel.Clients.ActiveDirectory/Platforms/net45/CustomWebBrowser.cs
WebBrowserNavigateErrorEventHandler  was in Microsoft.IdentityModel.Clients.ActiveDirectory.Internal in ADAL.Net 3.17.3, and therefore changing the namespace of all this file to Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Platform constituted a public API breaking change (even if the delegate was not used by customers)
Restoring the namespace for this type only (WebBrowserNavigateErrorEventHandler) to fix #954
> WebBrowserNavigateErrorEventHandler namespace change breaks public API

- src/Microsoft.IdentityModel.Clients.ActiveDirectory/Internal/Flows/AcquireTokenHandlerBase.cs
- src/Microsoft.IdentityModel.Clients.ActiveDirectory/Internal/Flows/AcquireTokenInteractiveHandler.cs
- src/Microsoft.IdentityModel.Clients.ActiveDirectory/Platforms/android/AuthenticationRequest.cs
- src/Microsoft.IdentityModel.Clients.ActiveDirectory/Platforms/android/BrokerConstants.cs
- src/Microsoft.IdentityModel.Clients.ActiveDirectory/Platforms/android/BrokerProxy.cs
- Sending correct user id to android broker for the case of silent flow + user id of Unique Type
- Fixing issue with always sending skip cache parameter to IOS Broker
- sending caller.info.package and caller.info.uid  to android Broker as hot fix to "recent" breaking change from they side
- use AssemblyFileVersion instead of AssemblyVersion as value for ClientVersion broker parameter
> fixing issues related to incorrect parameters send in broker requests

- adal/src/Microsoft.IdentityModel.Clients.ActiveDirectory/Features/WinCommon/AdalLogger.cs
Addressing issue #1028 - removing Console.WriteLine. Now default logging on NetStandard1.2 will not log to the Console, but logging can still be pushed to the console by setting the callback
> Removing Console.WriteLine from WinCommon

- changelog.txt
- src/Microsoft.IdentityModel.Clients.ActiveDirectory/Platforms/iOS/WebUI.cs
- src/Microsoft.IdentityModel.Clients.ActiveDirectory/Platforms/net45/DeviceAuthHelper.cs
- src/Microsoft.IdentityModel.Clients.ActiveDirectory/Platforms/winrt/DeviceAuthHelper.cs
- src/Microsoft.IdentityModel.Clients.ActiveDirectory/Properties/AssemblyInfo.cs
Merging Master into Adalv3/dev (update to 3.19.6)
Release of 3.19.2
Hotfix for CoreCLR writing to console by default and update to changelog for release 3.19.3 (#1034)
Hotfix (#1035)
* Hotfix for CoreCLR writing to console by default and update to changelog for release 3.19.3
* Change assembly file version to 3.19.3.0
Hotfix #1043 (#1045)
* Adding X5c claim to AcquireTokenByAuthorizationCodeAsync
for easy certificate rollover and parity with AcquireTokenAsync
* Filter logs for AdalEventSource based on log level in default log #1039
* Updating version to 3.19.4.0
Update changelog.txt
Trwalke/ios background thread fix (#1053)
* Resolved issue with iOS 11.3 where network resources are reclaimed by the system when sending an app to the background.
437419
* Clean Up
* Making field private. …
> Merging Master into Adalv3/dev (update to 3.19.6)
